version: '3.8'

services:
  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist data

  graphql-engine:
    image: hasura/graphql-engine:v2.42.0
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydb
      HASURA_GRAPHQL_ADMIN_SECRET: youradminsecret
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # Enable Hasura console
      HASURA_GRAPHQL_DEV_MODE: "true"  # Dev mode for debugging

  my-go-app:
    build:
      context: ./go  # Point to the 'go' directory where your Go app is located
      dockerfile: Dockerfile  # Assuming the Dockerfile is named 'Dockerfile'
    ports:
      - "8082:8080"  # Change this to the port your Go app listens to
    depends_on:
      - postgres

volumes:
  db_data:  # Volume for Postgres data persistence
